// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbfwljwpnfdcdqaiaalo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZndsandwbmZkY2RxYWlhYWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTIxMDcsImV4cCI6MjA2NzMyODEwN30.3N_6e-7Dk9uckWk_FOgN-dqHLMM0-ofdnchSLSFxReg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});